/** @class Array */
/** @class Element */
/** @class HTMLSelectElement */
/** @class Date */
/** @class Document */
/** @class Window */
/** @class Image */
/** @class Object */
/** @class String */
/** @class Promise */
