on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Merge JS Files
        run: |
          mkdir out
          find . -type f -name '*.js' ! -name 'Shorthand.js' -exec cat {} + > out/Shorthand.js

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
        
      - name: Upload Merged
        uses: actions/upload-artifact@v4
        with:
          name: js-artifact
          path: out/Shorthand.js
          retention-days: 90

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./out
          recurse: false
          output_dir: ./out

      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out/'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
     
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@latest
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ steps.date.outputs.date }}
#          release_name: Release ${{ steps.date.outputs.date }}
#          body: |
#            For changes check commit history
#          draft: false
#          prerelease: false

#      - name: Upload Release Asset
#        id: upload-release-asset 
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: ./out/Shorthand.js
#          asset_name: Shorthand.js
#          asset_content_type: text/javascript*/
